version: '3.8'

services:
  taller7:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5034:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
      - /app/bin
      - /app/obj